import type { GovernmentServiceMetadata, ServiceCategory } from "../types/governmentService";

export const GOVERNMENT_SERVICES_REGISTRY: Record<string, GovernmentServiceMetadata> = {
  // ==========================================
  // EDUCATION SERVICES
  // ==========================================
  "education-welfare": {
    serviceId: "education-welfare",
    serviceName: "Education Welfare Schemes",
    category: "education",
    provider: "Ministry of Education / Department of Higher Education",
    description: "Education support, fee relief, and student welfare schemes available through official departments",
    apiAvailability: "sandbox_only",
    connectorType: "educationConnector",
    endpointConfig: {
      baseUrlEnvVar: "GOV_EDUCATION_API_URL",
      path: "/schemes/education-welfare/requests",
      method: "POST",
    },
    authMethod: "sandbox",
    requiredCitizenConsent: {
      title: "Education Welfare Service Request",
      purpose: "Share only the information required by the selected education department or scheme.",
      recipientDepartment: "Selected Education Department or Scheme Authority",
    },
    requiredFields: [
      "citizenId",
      "stateCode",
      "serviceType",
    ],
    supportedOperations: ["submit_request", "track_status", "verify_eligibility"],
    timeoutMs: 4000,
    retryPolicy: { maxRetries: 3, initialBackoffMs: 800, exponential: true },
    status: "Sandbox",
  },
  "academic-records": {
    serviceId: "academic-records",
    serviceName: "Academic Records & Marksheet Verification",
    category: "education",
    provider: "DigiLocker / National Academic Depository (NAD)",
    description: "Verified academic transcripts, 10th/12th marksheets, and degree certificates",
    apiAvailability: "restricted_credentials",
    connectorType: "educationConnector",
    endpointConfig: {
      baseUrlEnvVar: "DIGILOCKER_API_URL",
      path: "/pull/academic/records",
      method: "POST",
    },
    authMethod: "oauth2",
    requiredCitizenConsent: {
      title: "DigiLocker Document Verification Access",
      purpose: "Authorize GovFix to retrieve digitally signed certificates from university depositories.",
      recipientDepartment: "National Academic Depository",
    },
    requiredFields: ["rollNumber", "passingYear", "boardOrUniversity", "examType"],
    supportedOperations: ["pull_certificate", "verify_signature"],
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, initialBackoffMs: 1000, exponential: true },
    status: "Requires Authorization",
  },
  "admissions": {
    serviceId: "admissions",
    serviceName: "Central Admissions Portal",
    category: "education",
    provider: "Samarth eGov / Central University Entrance Test (CUET)",
    description: "Counseling registration, state higher education admission, and seat confirmation",
    apiAvailability: "restricted_credentials",
    connectorType: "educationConnector",
    endpointConfig: {
      baseUrlEnvVar: "SAMARTH_API_URL",
      path: "/admissions/counseling/register",
      method: "POST",
    },
    authMethod: "api_key",
    requiredCitizenConsent: {
      title: "Counseling Registration & Score Sharing",
      purpose: "Share entrance rank and eligibility category with participating universities.",
      recipientDepartment: "National Testing Agency & University Consortium",
    },
    requiredFields: ["applicationNumber", "candidateName", "selectedProgram", "preferenceOrder"],
    supportedOperations: ["register_counseling", "check_allotment"],
    timeoutMs: 6000,
    retryPolicy: { maxRetries: 2, initialBackoffMs: 1000, exponential: true },
    status: "Requires Authorization",
  },
  "education-schemes": {
    serviceId: "education-schemes",
    serviceName: "State Education Welfare Schemes",
    category: "education",
    provider: "State Higher Education Council",
    description: "Student Credit Card Scheme, Fee Reimbursement, and Book Grant support",
    apiAvailability: "planned",
    connectorType: "educationConnector",
    endpointConfig: {
      baseUrlEnvVar: "STATE_EDU_API_URL",
      path: "/schemes/welfare/claims",
      method: "POST",
    },
    authMethod: "dbt_token",
    requiredCitizenConsent: {
      title: "State Education Grant Verification",
      purpose: "Verify college fee structures and student eligibility for fee concession.",
      recipientDepartment: "State Higher Education Department",
    },
    requiredFields: ["studentId", "institutionCode", "schemeCode"],
    supportedOperations: ["apply_scheme", "check_disbursement"],
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 3, initialBackoffMs: 800, exponential: true },
    status: "Connector Configured",
  },

  // ==========================================
  // TRANSPORT SERVICES
  // ==========================================
  "driving-licence": {
    serviceId: "driving-licence",
    serviceName: "Driving Licence Services",
    category: "transport",
    provider: "Ministry of Road Transport & Highways (MoRTH) / Sarathi",
    description: "Sarathi Parivahan portal — Renewal, endorsement, and address update",
    apiAvailability: "restricted_credentials",
    connectorType: "transportConnector",
    endpointConfig: {
      baseUrlEnvVar: "SARATHI_API_URL",
      path: "/sarathi/v2/dl-services",
      method: "POST",
    },
    authMethod: "oauth2",
    requiredCitizenConsent: {
      title: "Sarathi Driving Record Verification",
      purpose: "Retrieve licence validity, biometric photo match, and register renewal applications.",
      recipientDepartment: "State Regional Transport Authority (RTO)",
    },
    requiredFields: ["licenceNumber", "dateOfBirth", "rtoOfficeCode", "serviceRequestType"],
    supportedOperations: ["renew_dl", "verify_details", "slot_booking"],
    timeoutMs: 6000,
    retryPolicy: { maxRetries: 2, initialBackoffMs: 1000, exponential: true },
    status: "Requires Authorization",
  },
  "vehicle-registration": {
    serviceId: "vehicle-registration",
    serviceName: "Vehicle Registration (Vahan)",
    category: "transport",
    provider: "Ministry of Road Transport & Highways (MoRTH) / Vahan",
    description: "Vahan portal — Registration Certificate (RC) lookup, fitness status, and ownership transfer",
    apiAvailability: "restricted_credentials",
    connectorType: "transportConnector",
    endpointConfig: {
      baseUrlEnvVar: "VAHAN_API_URL",
      path: "/vahan/v4/rc-details",
      method: "POST",
    },
    authMethod: "api_key",
    requiredCitizenConsent: {
      title: "Vahan Vehicle Record Access",
      purpose: "Verify vehicle ownership, insurance coverage, and pollution fitness records.",
      recipientDepartment: "Ministry of Road Transport & Highways",
    },
    requiredFields: ["registrationNumber", "chassisNumberLast5"],
    supportedOperations: ["fetch_rc", "request_fitness", "change_address"],
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, initialBackoffMs: 800, exponential: true },
    status: "Requires Authorization",
  },
  "traffic-challan": {
    serviceId: "traffic-challan",
    serviceName: "Traffic e-Challan Settlement",
    category: "transport",
    provider: "MoRTH & State Traffic Police Department",
    description: "e-Challan violation verification, evidence photograph view, and direct settlement",
    apiAvailability: "sandbox_only",
    connectorType: "transportConnector",
    endpointConfig: {
      baseUrlEnvVar: "ECHALLAN_API_URL",
      path: "/challans/lookup",
      method: "POST",
    },
    authMethod: "sandbox",
    requiredCitizenConsent: {
      title: "Traffic Violation Settlement Consent",
      purpose: "Authorize vehicle registration lookup to fetch and dispute or pay traffic citations.",
      recipientDepartment: "Traffic Police Directorate",
    },
    requiredFields: ["vehicleOrChallanNumber"],
    supportedOperations: ["query_challans", "settle_challan"],
    timeoutMs: 4000,
    retryPolicy: { maxRetries: 3, initialBackoffMs: 600, exponential: true },
    status: "Sandbox",
  },
  "public-transport": {
    serviceId: "public-transport",
    serviceName: "Public Transit Smart Cards & Passes",
    category: "transport",
    provider: "National Common Mobility Card (NCMC) / State Transport Undertakings",
    description: "Metro card recharge, student bus concession pass, and smart card renewal",
    apiAvailability: "planned",
    connectorType: "transportConnector",
    endpointConfig: {
      baseUrlEnvVar: "NCMC_API_URL",
      path: "/transit/ncmc/balance",
      method: "POST",
    },
    authMethod: "api_key",
    requiredCitizenConsent: {
      title: "Transit Pass Recharge Authorization",
      purpose: "Access smart card balance and transit concession validity.",
      recipientDepartment: "Metropolitan Transit Corporation",
    },
    requiredFields: ["cardNumber", "operatorCode"],
    supportedOperations: ["check_balance", "recharge_pass"],
    timeoutMs: 4000,
    retryPolicy: { maxRetries: 2, initialBackoffMs: 800, exponential: true },
    status: "Connector Configured",
  },

  // ==========================================
  // UTILITY SERVICES
  // ==========================================
  "electricity-bill": {
    serviceId: "electricity-bill",
    serviceName: "Electricity Supply & Bill Settlement",
    category: "utilities",
    provider: "State Electricity Distribution Companies (DISCOMs)",
    description: "Monthly consumption review, subsidized tariff claims, and online bill payment",
    apiAvailability: "sandbox_only",
    connectorType: "utilityConnector",
    endpointConfig: {
      baseUrlEnvVar: "DISCOM_API_URL",
      path: "/billing/consumer/fetch",
      method: "POST",
    },
    authMethod: "sandbox",
    requiredCitizenConsent: {
      title: "Electricity Board Account Settlement",
      purpose: "Retrieve consumer power meter readings, outstanding dues, and process tariff subsidies.",
      recipientDepartment: "State Electricity Distribution Utility",
    },
    requiredFields: ["consumerId", "discomCode"],
    supportedOperations: ["fetch_bill", "settle_bill", "claim_subsidy"],
    timeoutMs: 4500,
    retryPolicy: { maxRetries: 3, initialBackoffMs: 700, exponential: true },
    status: "Sandbox",
  },
  "water-bill": {
    serviceId: "water-bill",
    serviceName: "Municipal Water Supply Services",
    category: "utilities",
    provider: "Municipal Water Supply & Sewerage Board (BWSSB/DJB)",
    description: "Meter reading records, bill verification, and new pipe connection applications",
    apiAvailability: "restricted_credentials",
    connectorType: "utilityConnector",
    endpointConfig: {
      baseUrlEnvVar: "WATER_BOARD_API_URL",
      path: "/water/consumer/query",
      method: "POST",
    },
    authMethod: "api_key",
    requiredCitizenConsent: {
      title: "Water Utility Account Verification",
      purpose: "Access connection records and process water meter billing settlement.",
      recipientDepartment: "Municipal Water Supply Board",
    },
    requiredFields: ["connectionNumber", "subdivisionCode"],
    supportedOperations: ["fetch_bill", "pay_bill"],
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, initialBackoffMs: 1000, exponential: true },
    status: "Requires Authorization",
  },
  "gas-services": {
    serviceId: "gas-services",
    serviceName: "LPG & Piped Natural Gas Services",
    category: "utilities",
    provider: "Ministry of Petroleum & Natural Gas / OMCs (Indane, BharatGas, HP)",
    description: "Cylinder booking, PAHAL DBT-L subsidy transfer verification, and safety inspection",
    apiAvailability: "restricted_credentials",
    connectorType: "utilityConnector",
    endpointConfig: {
      baseUrlEnvVar: "MOPNG_API_URL",
      path: "/lpg/consumer/booking",
      method: "POST",
    },
    authMethod: "api_key",
    requiredCitizenConsent: {
      title: "LPG Consumer Subsidy & Booking Consent",
      purpose: "Verify 17-digit LPG ID and schedule refill dispatch under PAHAL Direct Subsidy.",
      recipientDepartment: "Oil Marketing Companies (IOCL/BPCL/HPCL)",
    },
    requiredFields: ["lpgId17Digit", "distributorCode"],
    supportedOperations: ["book_refill", "track_subsidy"],
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, initialBackoffMs: 800, exponential: true },
    status: "Requires Authorization",
  },

  // ==========================================
  // FINANCE SERVICES
  // ==========================================
  "income-tax": {
    serviceId: "income-tax",
    serviceName: "Income Tax Portal (e-Filing)",
    category: "finance",
    provider: "Central Board of Direct Taxes (CBDT) / Directorate of Systems",
    description: "ITR e-filing verification, refund status tracking, and Annual Information Statement (AIS)",
    apiAvailability: "restricted_credentials",
    connectorType: "financeConnector",
    endpointConfig: {
      baseUrlEnvVar: "INCOMETAX_API_URL",
      path: "/efiling/v2/returns/status",
      method: "POST",
    },
    authMethod: "oauth2",
    requiredCitizenConsent: {
      title: "Income Tax Department Authorization",
      purpose: "Verify assessment year returns, e-acknowledgment status, and tax refund dispatch.",
      recipientDepartment: "Income Tax Department (CBDT)",
    },
    requiredFields: ["assessmentYear", "panMasked", "acknowledgmentNumber"],
    supportedOperations: ["track_refund", "verify_itr_status"],
    timeoutMs: 6000,
    retryPolicy: { maxRetries: 2, initialBackoffMs: 1200, exponential: true },
    status: "Requires Authorization",
  },
  "property-tax": {
    serviceId: "property-tax",
    serviceName: "Municipal Property Tax Portal",
    category: "finance",
    provider: "Municipal Corporation Revenue Department",
    description: "Self-assessment property tax computation, receipt generation, and mutation requests",
    apiAvailability: "sandbox_only",
    connectorType: "financeConnector",
    endpointConfig: {
      baseUrlEnvVar: "PROPERTY_TAX_API_URL",
      path: "/municipal/tax/assessment",
      method: "POST",
    },
    authMethod: "sandbox",
    requiredCitizenConsent: {
      title: "Property Tax Assessment Verification",
      purpose: "Fetch property valuation, ward cess, and compute annual municipal dues.",
      recipientDepartment: "Municipal City Corporation",
    },
    requiredFields: ["propertyIdOrSAS", "wardNumber"],
    supportedOperations: ["calculate_tax", "pay_tax", "download_receipt"],
    timeoutMs: 4000,
    retryPolicy: { maxRetries: 3, initialBackoffMs: 600, exponential: true },
    status: "Sandbox",
  },
  "pension": {
    serviceId: "pension",
    serviceName: "National Pension System & Jeevan Pramaan",
    category: "finance",
    provider: "Pension Fund Regulatory and Development Authority (PFRDA)",
    description: "NPS Tier I/II statement, digital life certificate submission, and Atal Pension Yojana",
    apiAvailability: "restricted_credentials",
    connectorType: "financeConnector",
    endpointConfig: {
      baseUrlEnvVar: "PFRDA_API_URL",
      path: "/nps/subscriber/statement",
      method: "POST",
    },
    authMethod: "api_key",
    requiredCitizenConsent: {
      title: "PFRDA Pension Record Access",
      purpose: "Access PRAN portfolio valuation and verify annual life certificate status.",
      recipientDepartment: "PFRDA & Central Recordkeeping Agency",
    },
    requiredFields: ["pranNumber", "subscriberDob"],
    supportedOperations: ["fetch_portfolio", "verify_dlc"],
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, initialBackoffMs: 1000, exponential: true },
    status: "Requires Authorization",
  },
  "other-finance": {
    serviceId: "other-finance",
    serviceName: "Financial Inclusion & Subsidy Schemes",
    category: "finance",
    provider: "Department of Financial Services (DFS)",
    description: "Public Provident Fund (PPF), Sovereign Gold Bonds, and Jan Dhan account linking",
    apiAvailability: "planned",
    connectorType: "financeConnector",
    endpointConfig: {
      baseUrlEnvVar: "DFS_API_URL",
      path: "/inclusion/subsidy/schemes",
      method: "POST",
    },
    authMethod: "dbt_token",
    requiredCitizenConsent: {
      title: "Financial Scheme Linking Consent",
      purpose: "Verify basic savings account eligibility for interest subsidy benefits.",
      recipientDepartment: "Department of Financial Services",
    },
    requiredFields: ["schemeCode", "bankBranchIfsc"],
    supportedOperations: ["link_account", "view_subsidies"],
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, initialBackoffMs: 800, exponential: true },
    status: "Connector Configured",
  },

  // ==========================================
  // HEALTH SERVICES
  // ==========================================
  "health-records": {
    serviceId: "health-records",
    serviceName: "Ayushman Bharat Health Account (ABHA)",
    category: "health",
    provider: "National Health Authority (NHA) / Ayushman Bharat Digital Mission",
    description: "Digital health records, diagnostic lab reports, and linked electronic health IDs",
    apiAvailability: "sandbox_only",
    connectorType: "healthConnector",
    endpointConfig: {
      baseUrlEnvVar: "ABDM_API_URL",
      path: "/abdm/v0.5/consent/request",
      method: "POST",
    },
    authMethod: "sandbox",
    requiredCitizenConsent: {
      title: "ABDM Health Records Consent",
      purpose: "Exchange designated medical summaries with certified healthcare providers under HIP/HIU.",
      recipientDepartment: "National Health Authority",
    },
    requiredFields: ["abhaAddressOrNumber"],
    supportedOperations: ["fetch_records", "link_care_context"],
    timeoutMs: 4500,
    retryPolicy: { maxRetries: 3, initialBackoffMs: 700, exponential: true },
    status: "Sandbox",
  },
  "health-schemes": {
    serviceId: "health-schemes",
    serviceName: "PM-JAY Health Protection Scheme",
    category: "health",
    provider: "National Health Authority (NHA) / PM-JAY",
    description: "Ayushman Card verification, ₹5 Lakh cashless family hospital cover, and empanelled hospitals",
    apiAvailability: "restricted_credentials",
    connectorType: "healthConnector",
    endpointConfig: {
      baseUrlEnvVar: "PMJAY_API_URL",
      path: "/pmjay/beneficiary/verify",
      method: "POST",
    },
    authMethod: "api_key",
    requiredCitizenConsent: {
      title: "PM-JAY Scheme Eligibility Verification",
      purpose: "Check SECC deprivation database to confirm cashless family hospital coverage.",
      recipientDepartment: "National Health Authority",
    },
    requiredFields: ["rationCardOrAadhaarRef", "stateCode"],
    supportedOperations: ["verify_eligibility", "locate_hospital"],
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, initialBackoffMs: 1000, exponential: true },
    status: "Requires Authorization",
  },
  "appointments": {
    serviceId: "appointments",
    serviceName: "Hospital OPD & Teleconsultation (e-Sanjeevani)",
    category: "health",
    provider: "Ministry of Health & Family Welfare (MoHFW)",
    description: "National Teleconsultation Service, AIIMS OPD appointment scheduling, and e-Prescriptions",
    apiAvailability: "restricted_credentials",
    connectorType: "healthConnector",
    endpointConfig: {
      baseUrlEnvVar: "ESANJEEVANI_API_URL",
      path: "/ors/appointments/book",
      method: "POST",
    },
    authMethod: "oauth2",
    requiredCitizenConsent: {
      title: "Hospital Appointment Scheduling",
      purpose: "Transmit patient reference and preferred clinical department to reserve OPD slot.",
      recipientDepartment: "Online Registration System (ORS) & MoHFW",
    },
    requiredFields: ["hospitalCode", "departmentName", "appointmentDate"],
    supportedOperations: ["book_slot", "cancel_slot", "view_slip"],
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, initialBackoffMs: 800, exponential: true },
    status: "Requires Authorization",
  },

  // ==========================================
  // CITIZEN SERVICES
  // ==========================================
  "certificates": {
    serviceId: "certificates",
    serviceName: "Revenue Certificate Services",
    category: "services",
    provider: "State Department of Revenue / e-District",
    description: "Income, Caste, Domicile, Non-Creamy Layer, and Birth/Death certificate issuance",
    apiAvailability: "sandbox_only",
    connectorType: "citizenServicesConnector",
    endpointConfig: {
      baseUrlEnvVar: "EDISTRICT_API_URL",
      path: "/revenue/certificates/apply",
      method: "POST",
    },
    authMethod: "sandbox",
    requiredCitizenConsent: {
      title: "Revenue Certificate Issuance Verification",
      purpose: "Submit applicant residential and taluk verification to the Tahsildar / Revenue Inspector.",
      recipientDepartment: "State Revenue Department",
    },
    requiredFields: ["certificateType", "applicantName", "talukCode", "annualFamilyIncome"],
    supportedOperations: ["apply_certificate", "track_certificate", "download_cert"],
    timeoutMs: 4000,
    retryPolicy: { maxRetries: 3, initialBackoffMs: 600, exponential: true },
    status: "Sandbox",
  },
  "citizen-schemes": {
    serviceId: "citizen-schemes",
    serviceName: "Welfare Scheme Registry & Direct Benefits",
    category: "services",
    provider: "Ministry of Rural Development & Ministry of Agriculture",
    description: "PM-Kisan Samman Nidhi, One Nation One Ration Card, and PMAY Housing Assistance",
    apiAvailability: "restricted_credentials",
    connectorType: "citizenServicesConnector",
    endpointConfig: {
      baseUrlEnvVar: "PMKISAN_API_URL",
      path: "/dbt/schemes/status",
      method: "POST",
    },
    authMethod: "api_key",
    requiredCitizenConsent: {
      title: "Direct Benefit Transfer Verification",
      purpose: "Verify agricultural land record registration and Aadhaar-seeded bank credit status.",
      recipientDepartment: "Ministry of Agriculture & Farmers Welfare",
    },
    requiredFields: ["farmerRegistrationOrRefId", "stateCode"],
    supportedOperations: ["check_installment", "update_ekyc"],
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, initialBackoffMs: 1000, exponential: true },
    status: "Requires Authorization",
  },
  "identity-services": {
    serviceId: "identity-services",
    serviceName: "Identity Services & Aadhaar e-KYC",
    category: "services",
    provider: "Unique Identification Authority of India (UIDAI) / State e-Gov",
    description: "Aadhaar e-KYC status, PAN-Aadhaar linkage confirmation, and National Voter Services",
    apiAvailability: "restricted_credentials",
    connectorType: "citizenServicesConnector",
    endpointConfig: {
      baseUrlEnvVar: "UIDAI_KYC_API_URL",
      path: "/kyc/verify/status",
      method: "POST",
    },
    authMethod: "oauth2",
    requiredCitizenConsent: {
      title: "Identity Verification & e-KYC Audit",
      purpose: "Request demographic verification and OTP authentication with the national registry.",
      recipientDepartment: "UIDAI & Election Commission of India",
    },
    requiredFields: ["identityReferenceToken", "verificationType"],
    supportedOperations: ["verify_status", "check_linking"],
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, initialBackoffMs: 800, exponential: true },
    status: "Requires Authorization",
  },
};

export function getServiceById(serviceId: string): GovernmentServiceMetadata | undefined {
  return GOVERNMENT_SERVICES_REGISTRY[serviceId];
}

export function getServicesByCategory(category: ServiceCategory): GovernmentServiceMetadata[] {
  return Object.values(GOVERNMENT_SERVICES_REGISTRY).filter((s) => s.category === category);
}

export function getAllRegisteredServices(): GovernmentServiceMetadata[] {
  return Object.values(GOVERNMENT_SERVICES_REGISTRY);
}
